name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DEPLOY_BRANCH: master
  GODOT_VERSION: 4.6.2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Stage .NET build
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: git add -f Build

      - name: Commit .NET build
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: git diff --quiet && git diff --staged --quiet || git commit -m "Update .NET build at $(TZ='Europe/Brussels' date +'%Y-%m-%d %H:%M:%S')"

      - name: Push .NET build
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: git push origin HEAD:${{ env.DEPLOY_BRANCH }}

      - name: Upload .NET build
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: Build/
          retention-days: 1
  godot:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.DEPLOY_BRANCH }}

      - name: Download .NET build
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        uses: actions/download-artifact@v4
        with:
          name: dotnet-build
          path: Build/
          
      - name: Configure git
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Setup Godot
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: |
          wget https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          unzip Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          mv Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 /usr/local/bin/godot
          chmod +x /usr/local/bin/godot

      - name: Setup Godot export templates
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: |
            mkdir -p ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
            wget https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
            unzip Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
            mv templates/* ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable/
            
      - name: Export Godot project
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: |
            mkdir -p Game/.godot/editor
            mkdir -p Game/.godot/imported
            godot --headless --path Game --export-debug "Windows Desktop" ../Build/TankDestroyer.exe

      - name: Stage Godot build
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: git add -f Build

      - name: Commit Godot build
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: git diff --quiet && git diff --staged --quiet || git commit -m "Update Godot build at $(TZ='Europe/Brussels' date +'%Y-%m-%d %H:%M:%S')"

      - name: Push Godot build
        if: github.ref == format('refs/heads/{0}', env.DEPLOY_BRANCH)
        run: git push origin HEAD:${{ env.DEPLOY_BRANCH }}