# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "Pipeline-test-branch" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: stage changed files
        if: github.ref == 'refs/heads/Pipeline-test-branch'
        run: git add -f Build
      - name: commit changed files
        if: github.ref == 'refs/heads/Pipeline-test-branch'
        run: git diff --quiet && git diff --staged --quiet || git commit -m "Update buildfolder at $(TZ='Europe/Brussels' date +'%Y-%m-%d %H:%M:%S')"
      - name: push code
        if: github.ref == 'refs/heads/Pipeline-test-branch'
        run: git push origin HEAD:Pipeline-test-branch