name: Export Godot Project and Commit

permissions:
  contents: write

on:
  push:
    branches: [ master ]
    paths:
      - 'Source/**'
      - 'Game/**'

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 💽 Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        # Use the .NET SDK from global.json in the root of the repository.
        global-json-file: global.json
    
    - name: 📦 Restore Dependencies
      run: dotnet restore

    - uses: chickensoft-games/setup-godot@v2
      name: 🤖 Setup Godot
      with:
          # Version must include major, minor, and patch, and be >= 4.0.0
          # Pre-release label is optional.
        version: 4.6.2 # also valid: 4.0.0.rc1 or 4.0.0 or "global.json", etc
          # Use .NET-enabled version of Godot (the default is also true).
        use-dotnet: true
          # Include the Godot Export Templates (the default is false).
        include-templates: true


    - name: 🔬 Verify Setup
      run: |
        dotnet --version
        godot --version

    - name: Export Game
      run: |
        cd Game
        godot --headless --export-release "Windows Desktop" --quit || exit 0


    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_prefix: "[AUTO-COMMIT] "
        commit_message: "Update build folder with godot export"